version: '3.0'
services:
  docker-mysql:
    restart: always
    container_name: mysql-container
    image: mysql
    environment:
      MYSQL_DATABASE: covid19db
      MYSQL_ROOT_PASSWORD: erick0
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.b
    ports:
      - "6033:3306"
    healthcheck:
      test: "usr/bin/mysql -u root -p erick0 --excecute \" SHOW DATABASES; \""
      interval: 2s
      timeout: 20s
      retries: 10
  web-app:
    restart: on-failure
    build: ./
    expose: 
      - "8080"
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - docker-mysql
